/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#cda9f6',
        'surface-bright': '#39393b',
        'primary-container': '#6b4c9a',
        'surface-container': '#201f21',
        'on-tertiary-container': '#493f00',
        'on-primary-fixed-variant': '#553683',
        'secondary-fixed': '#efdbff',
        'on-surface': '#e5e1e4',
        'on-error-container': '#ffdad6',
        'tertiary': '#d9c767',
        'surface-variant': '#353437',
        'primary-fixed': '#ecdcff',
        'tertiary-container': '#bdac4f',
        'surface-tint': '#d6baff',
        'on-primary-container': '#e1cbff',
        'secondary-fixed-dim': '#dab9ff',
        'error': '#ffb4ab',
        'on-secondary-fixed': '#29054d',
        'on-background': '#e5e1e4',
        'inverse-on-surface': '#303032',
        'tertiary-fixed-dim': '#d9c767',
        'outline-variant': '#4a4550',
        'primary': '#d6baff',
        'inverse-primary': '#6e4f9d',
        'surface-container-high': '#2a2a2c',
        'primary-fixed-dim': '#d6baff',
        'on-secondary': '#3f2063',
        'surface': '#131315',
        'on-tertiary-fixed': '#211c00',
        'outline': '#958e9b',
        'surface-container-lowest': '#0e0e10',
        'error-container': '#93000a',
        'secondary': '#dab9ff',
        'on-surface-variant': '#ccc3d1',
        'background': '#131315',
        'secondary-container': '#593a7e',
        'on-primary-fixed': '#280155',
        'on-tertiary-fixed-variant': '#514700',
        'on-secondary-fixed-variant': '#57387b',
        'surface-container-low': '#1b1b1d',
        'on-primary': '#3e1e6b',
        'tertiary-fixed': '#f6e380',
        'on-error': '#690005',
        'surface-dim': '#131315',
        'inverse-surface': '#e5e1e4',
        'surface-container-highest': '#353437',
        'on-tertiary': '#383000',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
